### ISSUE TITLE
8 failing tests

### ISSUE THREAD

**Issue by glampr** [radar/dotiw#40]
Just tried to use the gem but there are 8 failing tests for me (ruby 2.1.1):

Just putting these here, I will try to investigate more when I have more time.

```
  1) A better distance_of_time_in_words distance of time 14515200 == 5 months and 15 days
     Failure/Error: expect(distance_of_time(number)).to eq(result)
       
       expected: "5 months and 15 days"
            got: "5 months and 14 days"
       
       (compared using ==)
     # ./spec/lib/dotiw_spec.rb:30:in `block (4 levels) in <top (required)>'

  2) A better distance_of_time_in_words real version should be 1 year, 2 months, 3 days, 4 hours, 5 minutes, and 6 seconds
     Failure/Error: expect(distance_of_time_in_words(start, finish, true)).to eq(output)
       
       expected: "1 year, 2 months, 3 days, 4 hours, 5 minutes, and 6 seconds"
            got: "1 year, 2 months, 3 days, 3 hours, 5 minutes, and 6 seconds"
       
       (compared using ==)
     # ./spec/lib/dotiw_spec.rb:101:in `block (4 levels) in <top (required)>'

  3) A better distance_of_time_in_words real version without finish time should be 5 months and 15 days
     Failure/Error: expect(distance_of_time_in_words(start)).to eq(output)
       
       expected: "5 months and 15 days"
            got: "5 months and 14 days"
       
       (compared using ==)
     # ./spec/lib/dotiw_spec.rb:148:in `block (5 levels) in <top (required)>'

  4) A better distance_of_time_in_words with output options should be 1 year - 2 months - 3 days - 4 hours - 5 minutes, and 6 seconds
     Failure/Error: expect(distance_of_time_in_words(start, finish, true, options)).to eq(output)
       
       expected: "1 year - 2 months - 3 days - 4 hours - 5 minutes, and 6 seconds"
            got: "1 year - 2 months - 3 days - 3 hours - 5 minutes, and 6 seconds"
       
       (compared using ==)
     # ./spec/lib/dotiw_spec.rb:232:in `block (4 levels) in <top (required)>'

  5) A better distance_of_time_in_words with output options should be 1 year, 2 months, 3 days, 4 hours, and 6 seconds
     Failure/Error: expect(distance_of_time_in_words(start, finish, true, options)).to eq(output)
       
       expected: "1 year, 2 months, 3 days, 4 hours, and 6 seconds"
            got: "1 year, 2 months, 3 days, 3 hours, and 6 seconds"
       
       (compared using ==)
     # ./spec/lib/dotiw_spec.rb:232:in `block (4 levels) in <top (required)>'

  6) A better distance_of_time_in_words with output options should be 1 year, 2 months, 3 days, 4 hours, 5 minutes, and 6 seconds
     Failure/Error: expect(distance_of_time_in_words(start, finish, true, options)).to eq(output)
       
       expected: "1 year, 2 months, 3 days, 4 hours, 5 minutes, and 6 seconds"
            got: "1 year, 2 months, 3 days, 3 hours, 5 minutes, and 6 seconds"
       
       (compared using ==)
     # ./spec/lib/dotiw_spec.rb:232:in `block (4 levels) in <top (required)>'

  7) A better distance_of_time_in_words with output options should be 1 year, 2 months, 3 days, 4 hours, 5 minutes, and 6 seconds
     Failure/Error: expect(distance_of_time_in_words(start, finish, true, options)).to eq(output)
       
       expected: "1 year, 2 months, 3 days, 4 hours, 5 minutes, and 6 seconds"
            got: "1 year, 2 months, 3 days, 3 hours, 5 minutes, and 6 seconds"
       
       (compared using ==)
     # ./spec/lib/dotiw_spec.rb:232:in `block (4 levels) in <top (required)>'

  8) A better distance_of_time_in_words with output options should be 1 year, 2 months, 3 days, 4 hours, and 6 seconds
     Failure/Error: expect(distance_of_time_in_words(start, finish, true, options)).to eq(output)
       
       expected: "1 year, 2 months, 3 days, 4 hours, and 6 seconds"
            got: "1 year, 2 months, 3 days, 3 hours, and 6 seconds"
       
       (compared using ==)
     # ./spec/lib/dotiw_spec.rb:232:in `block (4 levels) in <top (required)>'

```

**Comment by glampr** [comment]
Take a look at #41 and comment if you have time!
